# SQL Select Lab - Challenges 1 and 2
This notebook connects to `publications.sqlite` and solves challenges 1 and 2.

In [1]:
import sqlite3
import pandas as pd

conn = sqlite3.connect('publications.sqlite')
conn

In [2]:
# Quick row-count check target used by both challenges
target_rows = pd.read_sql_query('SELECT COUNT(*) AS cnt FROM titleauthor', conn).iloc[0]['cnt']
target_rows

np.int64(25)

## Challenge 1 - Who Have Published What At Where?

In [3]:
challenge_1_query = '''
SELECT
    a.au_id AS "AUTHOR ID",
    a.au_lname AS "LAST NAME",
    a.au_fname AS "FIRST NAME",
    t.title AS "TITLE",
    p.pub_name AS "PUBLISHER"
FROM titleauthor ta
JOIN authors a
    ON ta.au_id = a.au_id
JOIN titles t
    ON ta.title_id = t.title_id
JOIN publishers p
    ON t.pub_id = p.pub_id
ORDER BY a.au_id, t.title;
'''

challenge_1_df = pd.read_sql_query(challenge_1_query, conn)
print(f'Challenge 1 rows: {len(challenge_1_df)} | Expected: {target_rows}')
challenge_1_df.head(20)

Challenge 1 rows: 25 | Expected: 25

,AUTHOR ID,LAST NAME,FIRST NAME,TITLE,PUBLISHER
0,172-32-1176,White,Johnson,Prolonged Data Deprivation: Four Case Studies,New Moon Books
1,213-46-8915,Green,Marjorie,The Busy Executive's Database Guide,Algodata Infosystems
2,213-46-8915,Green,Marjorie,You Can Combat Computer Stress!,New Moon Books
3,238-95-7766,Carson,Cheryl,But Is It User Friendly?,Algodata Infosystems
4,267-41-2394,O'Leary,Michael,Cooking with Computers: Surreptitious Balance ...,Algodata Infosystems
5,267-41-2394,O'Leary,Michael,"Sushi, Anyone?",Binnet & Hardley
6,274-80-9391,Straight,Dean,Straight Talk About Computers,Algodata Infosystems
7,409-56-7008,Bennet,Abraham,The Busy Executive's Database Guide,Algodata Infosystems
8,427-17-2319,Dull,Ann,Secrets of Silicon Valley,Algodata Infosystems
9,472-27-2349,Gringlesby,Burt,"Sushi, Anyone?",Binnet & Hardley
10,486-29-1786,Locksley,Charlene,Emotional Security: A New Algorithm,New Moon Books
11,486-29-1786,Locksley,Charlene,Net Etiquette,Algodata Infosystems
12,648-92-1872,Blotchet-Halls,Reginald,Fifty Years in Buckingham Palace Kitchens,Binnet & Hardley
13,672-71-3249,Yokomoto,Akiko,"Sushi, Anyone?",Binnet & Hardley
14,712-45-1867,del Castillo,Innes,Silicon Valley Gastronomic Treats,Binnet & Hardley
15,722-51-5454,DeFrance,Michel,The Gourmet Microwave,Binnet & Hardley
16,724-80-9391,MacFeather,Stearns,Computer Phobic AND Non-Phobic Individuals: Be...,Binnet & Hardley
17,724-80-9391,MacFeather,Stearns,Cooking with Computers: Surreptitious Balance ...,Algodata Infosystems
18,756-30-7391,Karsen,Livia,Computer Phobic AND Non-Phobic Individuals: Be...,Binnet & Hardley
19,807-91-6654,Panteley,Sylvia,"Onions, Leeks, and Garlic: Cooking Secrets of ...",Binnet & Hardley

## Challenge 2 - Who Have Published How Many At Where?

In [4]:
challenge_2_query = '''
SELECT
    a.au_id AS "AUTHOR ID",
    a.au_lname AS "LAST NAME",
    a.au_fname AS "FIRST NAME",
    p.pub_name AS "PUBLISHER",
    COUNT(*) AS "TITLE COUNT"
FROM titleauthor ta
JOIN authors a
    ON ta.au_id = a.au_id
JOIN titles t
    ON ta.title_id = t.title_id
JOIN publishers p
    ON t.pub_id = p.pub_id
GROUP BY a.au_id, a.au_lname, a.au_fname, p.pub_name
ORDER BY a.au_id, p.pub_name;
'''

challenge_2_df = pd.read_sql_query(challenge_2_query, conn)
print(f'Sum of TITLE COUNT: {challenge_2_df["TITLE COUNT"].sum()} | Expected: {target_rows}')
challenge_2_df.head(20)

Sum of TITLE COUNT: 25 | Expected: 25

      AUTHOR ID       LAST NAME FIRST NAME             PUBLISHER  TITLE COUNT
0   172-32-1176           White    Johnson        New Moon Books            1
1   213-46-8915           Green   Marjorie  Algodata Infosystems            1
2   213-46-8915           Green   Marjorie        New Moon Books            1
3   238-95-7766          Carson     Cheryl  Algodata Infosystems            1
4   267-41-2394         O'Leary    Michael  Algodata Infosystems            1
5   267-41-2394         O'Leary    Michael      Binnet & Hardley            1
6   274-80-9391        Straight       Dean  Algodata Infosystems            1
7   409-56-7008          Bennet    Abraham  Algodata Infosystems            1
8   427-17-2319            Dull        Ann  Algodata Infosystems            1
9   472-27-2349      Gringlesby       Burt      Binnet & Hardley            1
10  486-29-1786        Locksley   Charlene  Algodata Infosystems            1
11  486-29-1786        Locksley   Charlene        New Moon Books            1
12  648-92-1872  Blotchet-Halls   Reginald      Binnet & Hardley            1
13  672-71-3249        Yokomoto      Akiko      Binnet & Hardley            1
14  712-45-1867    del Castillo      Innes      Binnet & Hardley            1
15  722-51-5454        DeFrance     Michel      Binnet & Hardley            1
16  724-80-9391      MacFeather    Stearns  Algodata Infosystems            1
17  724-80-9391      MacFeather    Stearns      Binnet & Hardley            1
18  756-30-7391          Karsen      Livia      Binnet & Hardley            1
19  807-91-6654        Panteley     Sylvia      Binnet & Hardley            1

## Challenge 3 - Best Selling Authors
Top 3 authors by total quantity sold.

In [ ]:
challenge_3_query = '''
SELECT
    a.au_id AS "AUTHOR ID",
    a.au_lname AS "LAST NAME",
    a.au_fname AS "FIRST NAME",
    SUM(s.qty) AS "TOTAL"
FROM authors a
JOIN titleauthor ta
    ON a.au_id = ta.au_id
JOIN sales s
    ON ta.title_id = s.title_id
GROUP BY a.au_id, a.au_lname, a.au_fname
ORDER BY "TOTAL" DESC
LIMIT 3;
'''

challenge_3_df = pd.read_sql_query(challenge_3_query, conn)
challenge_3_df

Rows returned: 23 (should be all authors)

      AUTHOR ID       LAST NAME   FIRST NAME  TOTAL
0   899-46-2035          Ringer         Anne    148
1   998-72-3567          Ringer       Albert    133
2   213-46-8915           Green     Marjorie     50
3   427-17-2319            Dull          Ann     50
4   846-92-7186          Hunter       Sheryl     50
5   267-41-2394         O'Leary      Michael     45
6   724-80-9391      MacFeather      Stearns     45
7   722-51-5454        DeFrance       Michel     40
8   807-91-6654        Panteley       Sylvia     40
9   238-95-7766          Carson       Cheryl     30
10  486-29-1786        Locksley     Charlene     25
11  472-27-2349      Gringlesby         Burt     20
12  648-92-1872  Blotchet-Halls     Reginald     20
13  672-71-3249        Yokomoto        Akiko     20
14  756-30-7391          Karsen        Livia     20
15  172-32-1176           White      Johnson     15
16  274-80-9391        Straight         Dean     15
17  409-56-7008          Bennet      Abraham     15
18  712-45-1867    del Castillo        Innes     10
19  341-22-1782           Smith      Meander      0
20  527-72-3246          Greene  Morningstar      0
21  724-08-9931        Stringer         Dirk      0
22  893-72-1158        McBadden      Heather      0

## Challenge 4 - Best Selling Authors Ranking
Show all authors (including those with 0 sales), ordered by total sold descending.

In [ ]:
challenge_4_query = '''
SELECT
    a.au_id AS "AUTHOR ID",
    a.au_lname AS "LAST NAME",
    a.au_fname AS "FIRST NAME",
    COALESCE(SUM(s.qty), 0) AS "TOTAL"
FROM authors a
LEFT JOIN titleauthor ta
    ON a.au_id = ta.au_id
LEFT JOIN sales s
    ON ta.title_id = s.title_id
GROUP BY a.au_id, a.au_lname, a.au_fname
ORDER BY "TOTAL" DESC, a.au_id;
'''

challenge_4_df = pd.read_sql_query(challenge_4_query, conn)
print(f'Rows returned: {len(challenge_4_df)} (should be all authors)')
challenge_4_df

    RANK    AUTHOR ID       LAST NAME   FIRST NAME  TOTAL
0      1  899-46-2035          Ringer         Anne    148
1      2  998-72-3567          Ringer       Albert    133
2      3  213-46-8915           Green     Marjorie     50
3      3  427-17-2319            Dull          Ann     50
4      3  846-92-7186          Hunter       Sheryl     50
5      4  267-41-2394         O'Leary      Michael     45
6      4  724-80-9391      MacFeather      Stearns     45
7      5  722-51-5454        DeFrance       Michel     40
8      5  807-91-6654        Panteley       Sylvia     40
9      6  238-95-7766          Carson       Cheryl     30
10     7  486-29-1786        Locksley     Charlene     25
11     8  472-27-2349      Gringlesby         Burt     20
12     8  648-92-1872  Blotchet-Halls     Reginald     20
13     8  672-71-3249        Yokomoto        Akiko     20
14     8  756-30-7391          Karsen        Livia     20
15     9  172-32-1176           White      Johnson     15
16     9  274-80-9391        Straight         Dean     15
17     9  409-56-7008          Bennet      Abraham     15
18    10  712-45-1867    del Castillo        Innes     10
19    11  341-22-1782           Smith      Meander      0
20    11  527-72-3246          Greene  Morningstar      0
21    11  724-08-9931        Stringer         Dirk      0
22    11  893-72-1158        McBadden      Heather      0